server:
  servlet:
    context-path: /elon/mybatisxml
  port: 10001

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/elon?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:log4j2.xml